export const SEND_MESSAGE = 'CHATTING/SEND';
export const FETCH_STARTED = 'CHATTING/HISTORY/FETCH_STARTED';
export const FETCH_SUCCESS = 'CHATTING/HISTORY/FETCH_SUCCESS';
export const FETCH_FAILURE = 'CHATTING/HISTORY/FETCH_FAILURE';
